### ISSUE TITLE
PreCommit Testing  Setup

### ISSUE THREAD

**Issue by RossAD** [AudibleBoulders/AudibleBoulders#19]

**Comment by alberthuynh91** [comment]
I heard we should not use Pomander because we can't  publish our app with it since HR made it? We should use pre-commit on npm instead.

**Comment by RossAD** [comment]
Sounds good to me

Slanté

**Comment by alberthuynh91** [comment]
This should be deleted or closed. I am using pre-commit instead of pomander to run the linters.
